/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sheik' at '4/3/16 2:56 PM' with Gradle 2.11
 *
 * @author sheik, @date 4/3/16 2:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
